spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Jwt
    username: user
    password: pwd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B625064536756
        expiration: 86400000 # a day
        refreshToken:
          expiration: 604800000 # 7 days
